# Datos de Florario: una sola fuente para la portada, el JavaScript del calendario,
# las páginas, los PDF, los .ics y el sitemap. Si cambias algo aquí, vuelve a ejecutar
# `python _build/build.py`.

SITE = {
    "url": "https://www.calendariodeflores.com",
    "name": "Florario",
    "brand": "Florario – Calendario de flores",
    # El año del title, el H1, la tabla de la portada y los PDF se calcula con la fecha del build
    # (build.py → HOY). Las fechas de publicación y revisión van en la cabecera de cada página
    # de _build/paginas/ ("published" y "updated"); esta es la de reserva si una página no la tiene.
    "published": "2026-09-28",
    # --- Rellena estos datos (el build avisa mientras queden corchetes) ---
    "author": "Héctor Abenia",
    "author_bio": "Desarrollador en formación (Desarrollo de Aplicaciones Multiplataforma). Creó Florario para reunir en un solo sitio las fechas en que se regalan flores en España y Latinoamérica, y contrasta cada fecha y cada trend con al menos dos medios de países distintos antes de publicarla.",
    # Perfiles públicos del autor (LinkedIn, GitHub, Instagram…): van en sameAs del JSON-LD.
    "author_sameAs": ["https://github.com/abenia26", "https://www.linkedin.com/in/h%C3%A9ctor-abenia-c%C3%A1mara-3b5a5b413/"],
    # Florista que revisa el contenido. Mientras haya corchetes no se muestra en ninguna página.
    "reviewer": {"name": "[…]", "business": "[…]", "city": "[…]", "url": "[…]"},
    "owner": "Héctor Abenia",
    "email": "abeniacamarahector@gmail.com",
}

COLORS = {
    "amarillo": {"hex": "#F2C230", "label": "Amarillo"},
    "rojo": {"hex": "#D7263D", "label": "Rojo"},
    "rosa": {"hex": "#EE7FA8", "label": "Rosa"},
    "azul": {"hex": "#3F72E0", "label": "Azul"},
    "morado": {"hex": "#8A4FD8", "label": "Morado"},
    "naranja": {"hex": "#F28C1B", "label": "Naranja"},
    "blanco": {"hex": "#F4F2EA", "label": "Blanco"},
}
TYPES = {"clasico": "Clásico", "trend": "Trend", "memoria": "Memoria"}
MONTHS = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto",
          "septiembre", "octubre", "noviembre", "diciembre"]
MONTH_SHORT = ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
MONTH_COLORS = ["#7C9CF0", "#E8475F", "#F2C230", "#F07A5A", "#EE7FA8", "#E4572E",
                "#2BB3A3", "#F59E6B", "#F2B705", "#3F72E0", "#8A4FD8", "#C8102E"]
WEEKDAYS = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]

# Fotos de imagenes/web/ (<file>-960/-640/-480 en AVIF y WebP, <file>-160.webp cuadrada).
# Los .jpg originales de imagenes/ se mantienen para og:image. Créditos en imagenes/CREDITOS.md.
IMAGES = {
    "rosa-roja": {"file": "rosa-roja", "w": 960, "h": 640,
        "alt": "Rosa roja abierta, la flor de San Valentín y de Sant Jordi",
        "alt_corto": "Rosa roja abierta",
        "author": "Petro Stelte", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Red-Rose-Sitia-Crete.jpg"},
    "rosa-rosa": {"file": "rosa-rosa-palido", "w": 960, "h": 960,
        "alt": "Rosa rosa pálido en un rosal, flor del Día de la Novia y del Rose Day coreano",
        "alt_corto": "Rosa rosa pálido en un rosal",
        "author": "Acabashi", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Pink_rose_bloom_of_a_climbing_rose_at_Boreham,_Essex,_England_1.jpg"},
    "ramo-rosas": {"file": "ramo-de-rosas-rosas", "w": 960, "h": 720,
        "alt": "Ramo de rosas rosas, un regalo clásico para San Valentín y el Día de las Madres",
        "alt_corto": "Ramo de rosas rosas",
        "author": "Jebulon", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Bouquet_de_roses_roses.jpg"},
    "ramo-tulipanes": {"file": "ramo-de-tulipanes-de-colores", "w": 960, "h": 720,
        "alt": "Ramo de tulipanes de colores, típico del Galentine’s Day y de la primavera",
        "alt_corto": "Ramo de tulipanes de colores",
        "author": "Gábor Juhász", "license": "CC0",
        "source": "https://commons.wikimedia.org/wiki/File:Tulip-bouquet-vienna_(Unsplash).jpg"},
    "mimosa": {"file": "mimosa-acacia-dealbata", "w": 960, "h": 720,
        "alt": "Ramas de mimosa con bolitas amarillas, la flor del 8 de marzo en Italia",
        "alt_corto": "Ramas de mimosa con bolitas amarillas",
        "author": "JMK", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Acacia_dealbata,_blomme,_Waterberg.jpg"},
    "girasol": {"file": "girasol-amarillo", "w": 960, "h": 960,
        "alt": "Girasol amarillo abierto, la flor del trend de flores amarillas del 21 de septiembre",
        "alt_corto": "Girasol amarillo abierto",
        "author": "Böhringer Friedrich", "license": "CC BY-SA 2.5",
        "source": "https://commons.wikimedia.org/wiki/File:Sonnenblume_Helianthus_1.JPG"},
    "muguet": {"file": "lirio-de-los-valles-muguet", "w": 960, "h": 1349,
        "alt": "Tallo de lirio de los valles (muguet) con campanillas blancas, la flor del 1 de mayo en Francia",
        "alt_corto": "Tallo de lirio de los valles (muguet) con campanillas blancas",
        "author": "Agnes Monkelbaan", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Lelietje-van-dalen_of_meiklokje_(Convallaria_majalis)._14-05-2021_(actm.)_01.jpg"},
    "clavel": {"file": "claveles-fucsia", "w": 960, "h": 643,
        "alt": "Claveles fucsia, la flor clásica del Día de la Madre",
        "alt_corto": "Claveles fucsia",
        "author": "Andy Mabbett", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Bright_pink_carnation_cultivar_-_2020-05-11_-_Andy_Mabbett_-_01.jpg"},
    "peonia": {"file": "peonia-rosa", "w": 960, "h": 960,
        "alt": "Peonía rosa abierta, flor de temporada en mayo para el Día de la Madre",
        "alt_corto": "Peonía rosa abierta",
        "author": "Acabashi", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Cottage_garden_pink_peony_bloom_at_Boreham,_Essex,_England.jpg"},
    "dalia": {"file": "dalia-roja-y-amarilla", "w": 960, "h": 960,
        "alt": "Dalia de pétalos rojos con el centro amarillo, la flor nacional de México y de temporada en otoño",
        "alt_corto": "Dalia roja y amarilla",
        "author": "Diego Delso", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Dahlia_x_hortensis,_jard%C3%ADn_bot%C3%A1nico_de_Tallinn,_Estonia,_2012-08-13,_DD_01.JPG"},
    "orquidea": {"file": "orquidea-fucsia", "w": 960, "h": 960,
        "alt": "Orquídea phalaenopsis fucsia sobre fondo oscuro, la planta con flor más regalada",
        "alt_corto": "Orquídea phalaenopsis fucsia",
        "author": "Uoaei1", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Phalaenopsis_Cultivar_Mini_01.jpg"},
    "lavanda": {"file": "lavanda-morada", "w": 960, "h": 960,
        "alt": "Espiga de lavanda morada en flor, de temporada a principios del verano",
        "alt_corto": "Espiga de lavanda morada",
        "author": "Ermell", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Lavendelbl%C3%BCte-20220619-RM-160923.jpg"},
    "gerbera": {"file": "gerbera-roja", "w": 960, "h": 960,
        "alt": "Gerbera roja con el centro oscuro, una flor alegre para cumpleaños y graduaciones",
        "alt_corto": "Gerbera roja",
        "author": "JLPC", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Gerbera_FR_2014.jpg"},
    "ranunculo": {"file": "ranunculo-blanco-y-rosa", "w": 960, "h": 960,
        "alt": "Ranúnculo blanco con el borde de los pétalos rosa, flor de invierno y primavera para ramos de novia",
        "alt_corto": "Ranúnculo blanco y rosa",
        "author": "JLPC", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Renoncule_a_FR_2013.jpg"},
    "alcatraz": {"file": "alcatraz-blanco", "w": 960, "h": 960,
        "alt": "Alcatraz o cala blanca con el espádice amarillo, flor de bodas y de condolencias",
        "alt_corto": "Alcatraz (cala) blanco",
        "author": "Alvesgaspar", "license": "CC BY 2.5",
        "source": "https://commons.wikimedia.org/wiki/File:Jarro-2.jpg"},
    "jazmin": {"file": "jazmin-blanco", "w": 960, "h": 960,
        "alt": "Flores blancas de jazmín con botones rosados, de olor intenso",
        "alt_corto": "Flores de jazmín blancas",
        "author": "Didier Descouens", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:(MHNT)_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg"},
    "gladiolo": {"file": "gladiolo-naranja", "w": 960, "h": 960,
        "alt": "Vara de gladiolo con flores naranjas y amarillas, la flor de agosto",
        "alt_corto": "Gladiolo naranja",
        "author": "Timothy A. Gonsalves", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Gladiolus_dalenii_flowers_bud_black_Ooty_Jul25_A7CR_06143.jpg"},
    "lilium": {"file": "lilium-blanco-y-rosa", "w": 960, "h": 786,
        "alt": "Lilium blanco y rosa, flor del Día de la Madre en Argentina y de los ramos de condolencias",
        "alt_corto": "Lilium blanco y rosa",
        "author": "Derek Ramsey (Ram-Man) · Chanticleer Garden", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Lilium_%27Marco_Polo%27_Flower_2580px.jpg"},
    "hortensia-azul": {"file": "hortensia-azul", "w": 960, "h": 960,
        "alt": "Hortensia azul y violeta, flor azul para el Día del Novio del 3 de octubre",
        "alt_corto": "Hortensia azul y violeta",
        "author": "Subhrajyoti07", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Blue_Hydrangea_(common_names_hydrangea_or_hortensia).jpg"},
    "crisantemo": {"file": "crisantemo-blanco", "w": 960, "h": 805,
        "alt": "Crisantemo blanco de pétalos largos, la flor de Todos los Santos",
        "alt_corto": "Crisantemo blanco de pétalos largos",
        "author": "阿橋 HQ", "license": "CC BY-SA 2.0",
        "source": "https://commons.wikimedia.org/wiki/File:%E8%8F%8A%E8%8A%B1-%E7%99%BD%E9%B6%B4_Chrysanthemum_morifolium_%27White_Crane%27_-%E5%8F%B0%E5%8C%97%E5%A3%AB%E6%9E%97%E5%AE%98%E9%82%B8_Taipei,_Taiwan-_(12010293154).jpg"},
    "cempasuchil": {"file": "flor-de-cempasuchil", "w": 960, "h": 655,
        "alt": "Flores de cempasúchil naranjas y amarillas, la flor de la ofrenda del Día de Muertos",
        "alt_corto": "Flores de cempasúchil naranjas y amarillas",
        "author": "Joydeep", "license": "CC BY-SA 3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Tagetes_erecta_30012013.jpg"},
    "violeta": {"file": "violeta-morada", "w": 960, "h": 720,
        "alt": "Violeta morada entre hojas, la flor del trend de flores moradas del 9 de noviembre",
        "alt_corto": "Violeta morada entre hojas",
        "author": "Uoaei1", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Viola_odorata_20210226.jpg"},
    "nochebuena": {"file": "flor-de-nochebuena-roja", "w": 960, "h": 640,
        "alt": "Plantas de nochebuena rojas, la flor mexicana de la Navidad que se celebra el 8 de diciembre",
        "alt_corto": "Plantas de nochebuena rojas",
        "author": "Vengolis", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Euphorbia_pulcherrima_0111.jpg"},
    "ramo-silvestre": {"file": "ramo-de-margaritas-y-flores-silvestres", "w": 960, "h": 640,
        "alt": "Ramo de margaritas y flores silvestres en un bote de cristal, un regalo para cualquier día",
        "alt_corto": "Ramo de margaritas y flores silvestres en un bote de cristal",
        "author": "Petro Stelte", "license": "CC BY-SA 4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Flower-bouquet-wild-flowers-Sitia-Crete-Greece.jpg"},
}

# Países con página propia (hreflang). code = región del hreflang.
COUNTRIES = {
    "ES": {"slug": "espana", "name": "España", "hreflang": "es-ES", "de": "de España", "en": "en España"},
    "MX": {"slug": "mexico", "name": "México", "hreflang": "es-MX", "de": "de México", "en": "en México"},
    "AR": {"slug": "argentina", "name": "Argentina", "hreflang": "es-AR", "de": "de Argentina", "en": "en Argentina"},
    "CO": {"slug": "colombia", "name": "Colombia", "hreflang": "es-CO", "de": "de Colombia", "en": "en Colombia"},
    "CL": {"slug": "chile", "name": "Chile", "hreflang": "es-CL", "de": "de Chile", "en": "en Chile"},
    "PE": {"slug": "peru", "name": "Perú", "hreflang": "es-PE", "de": "del Perú", "en": "en Perú"},
}
LATAM = ["MX", "AR", "CO", "CL", "PE"]

# m/d = fecha fija · rule = {m, wd (0 = domingo), n} = n-ésimo día de la semana del mes
# paises = países con página propia donde la fecha se celebra · guia = página que la explica
EVENTS = [
    {"id": "rose-day", "m": 2, "d": 7, "name": "Rose Day", "flower": "Rosas", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "India", "paises": [], "guia": "san-valentin",
     "story": "Abre la Valentine’s Week: los siete días previos a San Valentín tienen tema propio y el primero se dedica a regalar rosas. Muy presente en edits y reels de Bollywood."},
    {"id": "galentines", "m": 2, "d": 13, "name": "Galentine’s Day", "flower": "Ramos para tus amigas", "color": "rosa", "petals": 6, "type": "trend", "img": "ramo-tulipanes",
     "region": "Global, sobre todo en redes", "tag": "galentinesday", "paises": ["ES", "MX", "AR", "CO", "CL", "PE"], "guia": "san-valentin",
     "story": "Nació en 2010 en la serie Parks and Recreation: Leslie Knope celebra a sus amigas el día antes de San Valentín. Las redes lo convirtieron en plan real con desayuno, ramos compartidos y foto en grupo."},
    {"id": "san-valentin", "m": 2, "d": 14, "name": "San Valentín", "flower": "Rosas rojas", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "Global · en México y otros países, Día del Amor y la Amistad", "paises": ["ES", "MX", "AR", "CO", "CL", "PE"], "guia": "san-valentin",
     "story": "La fecha que más flores mueve en el año. La rosa roja es el código universal de “me gustas”; en varios países de Latinoamérica también se celebra la amistad, así que vale regalar a amigos."},
    {"id": "8m", "m": 3, "d": 8, "name": "Día Internacional de la Mujer", "flower": "Mimosa o tulipanes", "color": "amarillo", "petals": 8, "type": "clasico", "img": "mimosa",
     "region": "Italia, Rusia y Europa del Este", "paises": ["ES", "MX", "AR", "CO", "CL", "PE"], "guia": "dia-de-la-mujer",
     "story": "En Italia se regala una rama de mimosa desde 1946; en Rusia y Europa del Este son típicos los tulipanes. En España y Latinoamérica el 8M es sobre todo una jornada de reivindicación: si regalas flores, que sea como reconocimiento y no en lugar de escuchar."},
    {"id": "padre-es", "m": 3, "d": 19, "name": "Día del Padre", "flower": "Girasoles o una planta", "color": "amarillo", "petals": 10, "type": "clasico", "img": "girasol",
     "region": "España, Portugal, Italia, Bolivia y Honduras", "paises": ["ES"], "guia": "dia-del-padre",
     "story": "Coincide con San José, padre de Jesús en la tradición cristiana. Las flores no son el regalo más típico, pero cada vez más gente regala girasoles o una planta que dure: es un detalle que no se marchita en una semana."},
    {"id": "amarillas-marzo", "m": 3, "d": 21, "name": "Flores amarillas (primavera norte)", "flower": "Girasoles, tulipanes o rosas amarillas", "color": "amarillo", "petals": 10, "type": "trend", "img": "girasol",
     "region": "México y Centroamérica, cada vez más en Perú", "tag": "floresamarillas", "paises": ["MX", "PE"], "guia": "flores-amarillas-21-de-marzo",
     "song": {"title": "Flores amarillas", "by": "Floricienta (Florencia Bertotti), 2004"},
     "story": "El trend del 21 de septiembre se duplicó: con la llegada de la primavera al hemisferio norte, en México se adoptó un segundo día de flores amarillas. Misma canción, misma idea, otra estación."},
    {"id": "sant-jordi", "m": 4, "d": 23, "name": "Sant Jordi", "flower": "Una rosa roja y un libro", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "Cataluña", "paises": ["ES"], "guia": "sant-jordi",
     "story": "Según la leyenda, de la sangre del dragón que venció Sant Jordi brotó un rosal. Barcelona se llena de puestos de rosas y libros; el libro se sumó en el siglo XX y coincide con el Día Internacional del Libro."},
    {"id": "muguet", "m": 5, "d": 1, "name": "Muguet du 1er mai", "flower": "Lirio de los valles (muguet)", "color": "blanco", "petals": 6, "type": "clasico", "img": "muguet",
     "region": "Francia", "paises": [], "guia": "lirio-de-los-valles",
     "story": "Desde el rey Carlos IX (1561) se regala un ramito de muguet el 1 de mayo para desear suerte. Ese día la venta callejera de muguet está tolerada sin licencia."},
    {"id": "madre-es", "rule": {"m": 5, "wd": 0, "n": 1}, "ruleText": "1.er domingo de mayo", "name": "Día de la Madre", "flower": "Claveles, rosas o peonías", "color": "rosa", "petals": 8, "type": "clasico", "img": "peonia",
     "region": "España y Portugal", "paises": ["ES"], "guia": "dia-de-la-madre",
     "story": "En España se celebra el primer domingo de mayo, el mes que la tradición católica dedica a la Virgen. Claveles y peonías son los clásicos."},
    {"id": "madre-mx", "m": 5, "d": 10, "name": "Día de las Madres", "flower": "Rosas y claveles", "color": "rosa", "petals": 5, "type": "clasico", "img": "ramo-rosas",
     "region": "México, Guatemala y El Salvador", "paises": ["MX"], "guia": "dia-de-la-madre",
     "story": "En México es fecha fija desde 1922, cuando el periódico Excélsior impulsó la celebración. Serenata, comida familiar y un ramo que no puede faltar."},
    {"id": "madre-mayo2", "rule": {"m": 5, "wd": 0, "n": 2}, "ruleText": "2.º domingo de mayo", "name": "Día de la Madre", "flower": "Claveles", "color": "rosa", "petals": 8, "type": "clasico", "img": "clavel",
     "region": "EE. UU., Colombia, Perú, Chile, Venezuela, Brasil, Italia y más", "paises": ["CO", "CL", "PE"], "guia": "dia-de-la-madre",
     "story": "Anna Jarvis impulsó la fecha en EE. UU. en 1908 y eligió el clavel, la flor favorita de su madre. Desde ahí se extendió a buena parte de América y Europa."},
    {"id": "rose-day-kr", "m": 5, "d": 14, "name": "Rose Day", "flower": "Rosas", "color": "rosa", "petals": 5, "type": "clasico", "img": "rosa-rosa",
     "region": "Corea del Sur", "paises": [], "guia": "san-valentin",
     "story": "En Corea cada día 14 del mes tiene un tema para parejas. El de mayo es el de las rosas: si sigues K-dramas o K-pop, ya te sonará."},
    {"id": "maestro", "m": 5, "d": 15, "name": "Día del Maestro", "flower": "Margaritas, girasoles o una planta pequeña", "color": "amarillo", "petals": 12, "type": "clasico", "img": "ramo-silvestre",
     "region": "México y Colombia", "paises": ["MX", "CO"], "guia": "dia-del-maestro",
     "story": "México celebra a sus docentes cada 15 de mayo desde 1918, y Colombia el mismo día en recuerdo de San Juan Bautista de La Salle, patrono de los educadores. Una flor con una nota escrita a mano es el detalle más repetido en las aulas."},
    {"id": "namorados", "m": 6, "d": 12, "name": "Dia dos Namorados", "flower": "Rosas rojas", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "Brasil", "paises": [], "guia": "san-valentin",
     "story": "El San Valentín brasileño cae en la víspera de San Antonio, el santo casamentero. Se popularizó en 1949 con una campaña publicitaria y hoy es una de las fechas más fuertes del año allí."},
    {"id": "padre-junio", "rule": {"m": 6, "wd": 0, "n": 3}, "ruleText": "3.er domingo de junio", "name": "Día del Padre", "flower": "Girasoles, flores azules o una planta", "color": "azul", "petals": 6, "type": "clasico", "img": "girasol",
     "region": "México, Argentina, Chile, Colombia, Perú, Venezuela, EE. UU. y más", "paises": ["MX", "AR", "CO", "CL", "PE"], "guia": "dia-del-padre",
     "story": "La fecha de EE. UU., que se extendió a casi toda Latinoamérica. Las flores para papá ganan terreno gracias al trend de “ellos también merecen flores”: girasoles, tonos azules o una planta para la oficina."},
    {"id": "novia", "m": 8, "d": 1, "name": "Día de la Novia", "flower": "Rosas", "color": "rosa", "petals": 5, "type": "trend", "img": "rosa-rosa",
     "region": "México, Perú, Ecuador, Costa Rica", "tag": "diadelanovia", "paises": ["MX", "PE"], "guia": "dia-de-la-novia",
     "variant": "En algunos países se celebra el primer domingo de abril; el 1 de agosto es la versión que más circula en redes.",
     "story": "Viene del National Girlfriend Day estadounidense y en redes funciona como un segundo San Valentín. No es oficial en ningún país, pero las florerías ya lo tienen marcado."},
    {"id": "amor-amistad-co", "rule": {"m": 9, "wd": 6, "n": 3}, "ruleText": "3.er sábado de septiembre", "name": "Amor y Amistad", "flower": "Rosas y girasoles", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "Colombia", "paises": ["CO"], "guia": "amor-y-amistad",
     "story": "Colombia celebra su San Valentín en septiembre desde los años sesenta. Vale para pareja y para amigos, con amigo secreto incluido."},
    {"id": "amarillas", "m": 9, "d": 21, "name": "Flores amarillas", "flower": "Girasoles, tulipanes o rosas amarillas", "color": "amarillo", "petals": 10, "type": "trend", "img": "girasol",
     "region": "Toda Latinoamérica · empezó en Argentina, Chile, Perú y Uruguay", "tag": "floresamarillas", "paises": ["ES", "MX", "AR", "CO", "CL", "PE"], "guia": "flores-amarillas",
     "song": {"title": "Flores amarillas", "by": "Floricienta (Florencia Bertotti), 2004"},
     "variant": "Variante viral: el 22 para primas o tías, el 23 para mamá o abuela y el 24 para tu mejor amiga.",
     "story": "En Floricienta, la serie argentina de 2004, la protagonista sueña con que alguien le regale flores amarillas. En septiembre de 2021 TikTok recuperó la canción para recibir la primavera del hemisferio sur y el trend no ha parado desde entonces."},
    {"id": "novio", "m": 10, "d": 3, "name": "Día del Novio", "flower": "Flores azules o un ramo de Hot Wheels", "color": "azul", "petals": 6, "type": "trend", "img": "hortensia-azul",
     "region": "México, Perú, Chile, Colombia, España", "tag": "diadelnovio", "paises": ["ES", "MX", "CO", "CL", "PE"], "guia": "flores-azules",
     "story": "Nació en 2014 como #NationalBoyfriendDay y en Latinoamérica se volvió la respuesta a las flores amarillas: flores azules y ramos hechos con carritos Hot Wheels entre papel y listones."},
    {"id": "madre-ar", "rule": {"m": 10, "wd": 0, "n": 3}, "ruleText": "3.er domingo de octubre", "name": "Día de la Madre", "flower": "Rosas y liliums", "color": "rosa", "petals": 6, "type": "clasico", "img": "lilium",
     "region": "Argentina", "paises": ["AR"], "guia": "dia-de-la-madre",
     "story": "Argentina celebra a las madres en primavera, el tercer domingo de octubre, así que coincide con la mejor época de flores del hemisferio sur."},
    {"id": "todos-santos", "m": 11, "d": 1, "name": "Todos los Santos", "flower": "Crisantemos", "color": "blanco", "petals": 12, "type": "memoria", "img": "crisantemo",
     "region": "España y buena parte de Latinoamérica", "paises": ["ES", "CO", "CL", "PE"], "guia": "todos-los-santos-dia-de-muertos",
     "story": "Las familias limpian y adornan las tumbas de sus seres queridos. El crisantemo es la flor de esta fecha: llevarlo es una forma de decir que se les recuerda."},
    {"id": "muertos", "m": 11, "d": 2, "name": "Día de Muertos", "flower": "Cempasúchil", "color": "naranja", "petals": 12, "type": "memoria", "img": "cempasuchil",
     "region": "México", "paises": ["MX"], "guia": "todos-los-santos-dia-de-muertos",
     "story": "El color y el olor del cempasúchil marcan el camino de las almas hasta la ofrenda. Sus pétalos naranjas son uno de los símbolos visuales de la celebración."},
    {"id": "moradas", "m": 11, "d": 9, "name": "Flores moradas", "flower": "Violetas o cualquier flor morada", "color": "morado", "petals": 5, "type": "trend", "img": "violeta",
     "region": "México, Perú, Colombia, España", "tag": "floresmoradas", "paises": ["ES", "MX", "CO", "PE"], "guia": "flores-moradas",
     "song": {"title": "Un ramito de violetas", "by": "Cecilia, 1975 · versión viral de Zalo Reyes"},
     "variant": "En Colombia circula también la variante del 9 de octubre.",
     "story": "La canción cuenta que alguien enviaba violetas a una mujer cada 9 de noviembre, sin tarjeta; al final era su propio marido. En TikTok se regalan a tu “persona morada”: alguien que llegó hace poco y ya es imprescindible."},
    {"id": "hombre", "m": 11, "d": 19, "name": "Día Internacional del Hombre", "flower": "Flores azules, girasoles o Hot Wheels", "color": "azul", "petals": 8, "type": "trend", "img": "hortensia-azul",
     "region": "Latinoamérica, sobre todo en redes", "tag": "diadelhombre", "paises": ["MX", "AR", "CO", "CL", "PE"], "guia": "flores-azules",
     "story": "Se celebra desde 1999. En redes se popularizó la idea de que ellos también merecen flores: rosas azules, girasoles o ramos de Hot Wheels para romper la costumbre de que solo se regalan a mujeres."},
    {"id": "nochebuena", "m": 12, "d": 8, "name": "Día Nacional de la Nochebuena", "flower": "Flor de Nochebuena (cuetlaxóchitl)", "color": "rojo", "petals": 6, "type": "clasico", "img": "nochebuena",
     "region": "México", "paises": ["MX"], "guia": "nochebuena",
     "story": "La flor de Navidad es mexicana: en náhuatl se llama cuetlaxóchitl. El 8 de diciembre se celebra su origen y arranca la temporada de regalarla y decorar con ella."},
    {"id": "guadalupe", "m": 12, "d": 12, "name": "Virgen de Guadalupe", "flower": "Rosas", "color": "rojo", "petals": 5, "type": "clasico", "img": "rosa-roja",
     "region": "México", "paises": ["MX"], "guia": "virgen-de-guadalupe",
     "story": "Según la tradición, en 1531 Juan Diego llevó rosas del cerro del Tepeyac en su tilma, en pleno diciembre. Por eso cada 12 de diciembre millones de personas llevan rosas a la Basílica."},
]

# Flores de temporada por mes (orientativo: depende de la zona y del invernadero).
# Los nombres que coinciden con una página de flor se enlazan solos.
SEASON_REGIONS = [
    ("es", "España"),
    ("mx", "México y Centroamérica"),
    ("sur", "Argentina, Chile y Uruguay"),
]
SEASON = [
    {"es": ["mimosa", "anémona", "ranúnculo", "tulipán", "narciso", "camelia"],
     "mx": ["rosa", "alcatraz", "gerbera", "nube (gypsophila)", "clavel"],
     "sur": ["girasol", "hortensia", "agapanto", "lavanda", "gladiolo"]},
    {"es": ["mimosa", "tulipán", "anémona", "ranúnculo", "narciso", "violeta"],
     "mx": ["rosa", "alcatraz", "clavel", "gerbera", "girasol"],
     "sur": ["girasol", "dalia", "hortensia", "zinnia", "gladiolo"]},
    {"es": ["tulipán", "narciso", "ranúnculo", "fresia", "jacinto", "violeta"],
     "mx": ["girasol", "alcatraz", "margarita", "gerbera", "lilium"],
     "sur": ["dalia", "crisantemo", "rosa", "aster", "lisianthus"]},
    {"es": ["tulipán", "lila", "ranúnculo", "fresia", "alhelí", "rosa", "cala"],
     "mx": ["alcatraz", "lilium", "gerbera", "clavel", "margarita"],
     "sur": ["crisantemo", "rosa", "dalia", "aster", "lisianthus"]},
    {"es": ["peonía", "rosa", "clavel", "lila", "iris", "lirio de los valles", "cala"],
     "mx": ["rosa", "clavel", "lilium", "gerbera", "girasol"],
     "sur": ["crisantemo", "rosa", "camelia", "lilium", "alstroemeria"]},
    {"es": ["peonía", "rosa", "hortensia", "lavanda", "margarita", "girasol"],
     "mx": ["girasol", "gladiola", "nardo", "hortensia", "rosa"],
     "sur": ["camelia", "cala (alcatraz)", "alstroemeria", "clavel", "rosa"]},
    {"es": ["girasol", "lavanda", "hortensia", "dalia", "gladiolo", "zinnia"],
     "mx": ["girasol", "gladiola", "nardo", "dalia", "hortensia"],
     "sur": ["mimosa (aromo)", "camelia", "cala (alcatraz)", "jacinto", "clavel"]},
    {"es": ["girasol", "dalia", "gladiolo", "zinnia", "hortensia", "lisianthus"],
     "mx": ["dalia", "gladiola", "nardo", "girasol", "margarita"],
     "sur": ["mimosa (aromo)", "fresia", "narciso", "jacinto", "tulipán"]},
    {"es": ["dalia", "girasol", "rosa", "aster", "crisantemo", "hortensia"],
     "mx": ["dalia", "girasol", "cempasúchil (desde finales de mes)", "gerbera", "rosa"],
     "sur": ["fresia", "tulipán", "ranúnculo", "narciso", "lila", "girasol (de invernadero)"]},
    {"es": ["crisantemo", "dalia", "rosa", "aster", "hypericum"],
     "mx": ["cempasúchil", "terciopelo (mano de león)", "nube (gypsophila)", "crisantemo", "rosa"],
     "sur": ["rosa", "lilium", "lila", "alhelí", "ranúnculo"]},
    {"es": ["crisantemo", "anémona", "amarilis", "eléboro", "rosa"],
     "mx": ["cempasúchil", "terciopelo (mano de león)", "crisantemo", "nochebuena", "alcatraz"],
     "sur": ["peonía", "rosa", "lilium", "jazmín", "lavanda"]},
    {"es": ["flor de Pascua (nochebuena)", "amarilis", "anémona", "eléboro", "ranúnculo", "ciclamen"],
     "mx": ["nochebuena", "rosa", "alcatraz", "gerbera", "clavel"],
     "sur": ["hortensia", "lilium", "agapanto", "lavanda", "peonía"]},
]
SEASON_NOTE = ("En Colombia, Ecuador y la zona andina el clima de altura permite cultivar rosas, claveles, "
               "crisantemos, alstroemerias y hortensias todo el año: por eso son dos de los mayores "
               "exportadores de flores del mundo.")

# Páginas de flor: slug, nombre, foto, color y palabras de la tabla de temporada que enlazan a ella.
FLOWERS = [
    {"slug": "rosa", "name": "Rosa", "img": "rosa-roja", "color": "rojo", "match": ["rosa"]},
    {"slug": "girasol", "name": "Girasol", "img": "girasol", "color": "amarillo", "match": ["girasol"]},
    {"slug": "tulipan", "name": "Tulipán", "img": "ramo-tulipanes", "color": "rosa", "match": ["tulipán"]},
    {"slug": "peonia", "name": "Peonía", "img": "peonia", "color": "rosa", "match": ["peonía"]},
    {"slug": "clavel", "name": "Clavel", "img": "clavel", "color": "rosa", "match": ["clavel"]},
    {"slug": "margarita", "name": "Margarita", "img": "ramo-silvestre", "color": "blanco", "match": ["margarita"]},
    {"slug": "lilium", "name": "Lilium (azucena)", "img": "lilium", "color": "rosa", "match": ["lilium"]},
    {"slug": "hortensia", "name": "Hortensia", "img": "hortensia-azul", "color": "azul", "match": ["hortensia"]},
    {"slug": "violeta", "name": "Violeta", "img": "violeta", "color": "morado", "match": ["violeta"]},
    {"slug": "crisantemo", "name": "Crisantemo", "img": "crisantemo", "color": "blanco", "match": ["crisantemo"]},
    {"slug": "cempasuchil", "name": "Cempasúchil", "img": "cempasuchil", "color": "naranja", "match": ["cempasúchil"]},
    {"slug": "mimosa", "name": "Mimosa", "img": "mimosa", "color": "amarillo", "match": ["mimosa"]},
    {"slug": "lirio-de-los-valles", "name": "Lirio de los valles", "img": "muguet", "color": "blanco", "match": ["lirio de los valles"]},
    {"slug": "nochebuena", "name": "Nochebuena", "img": "nochebuena", "color": "rojo", "match": ["nochebuena", "flor de Pascua"]},
    {"slug": "dalia", "name": "Dalia", "img": "dalia", "color": "rojo", "match": ["dalia"]},
    {"slug": "orquidea", "name": "Orquídea", "img": "orquidea", "color": "rosa", "match": ["orquídea"]},
    {"slug": "lavanda", "name": "Lavanda", "img": "lavanda", "color": "morado", "match": ["lavanda"]},
    {"slug": "gerbera", "name": "Gerbera", "img": "gerbera", "color": "rojo", "match": ["gerbera"]},
    {"slug": "ranunculo", "name": "Ranúnculo", "img": "ranunculo", "color": "rosa", "match": ["ranúnculo"]},
    {"slug": "alcatraz", "name": "Alcatraz (cala)", "img": "alcatraz", "color": "blanco", "match": ["alcatraz", "cala"]},
    {"slug": "jazmin", "name": "Jazmín", "img": "jazmin", "color": "blanco", "match": ["jazmín"]},
    {"slug": "gladiolo", "name": "Gladiolo", "img": "gladiolo", "color": "naranja", "match": ["gladiolo", "gladiola"]},
]

# Guías (tarjetas, menú, pie). small = fechas en corto; desc = subtítulo de la tarjeta.
GUIDES = [
    {"slug": "flores-amarillas", "name": "Flores amarillas", "small": "21 sep", "desc": "Por qué se regalan el 21 de septiembre", "img": "girasol", "color": "amarillo"},
    {"slug": "flores-amarillas-21-de-marzo", "name": "Flores amarillas el 21 de marzo", "small": "21 mar", "desc": "La versión de primavera en México", "img": "girasol", "color": "amarillo"},
    {"slug": "flores-azules", "name": "Flores azules", "small": "3 oct · 19 nov", "desc": "Día del Novio, Hot Wheels y Día del Hombre", "img": "hortensia-azul", "color": "azul"},
    {"slug": "flores-moradas", "name": "Flores moradas", "small": "9 nov", "desc": "La persona morada y “Un ramito de violetas”", "img": "violeta", "color": "morado"},
    {"slug": "san-valentin", "name": "San Valentín", "small": "14 feb", "desc": "Rosas rojas y los otros San Valentín del año", "img": "ramo-rosas", "color": "rojo"},
    {"slug": "dia-de-la-mujer", "name": "Día de la Mujer (8M)", "small": "8 mar", "desc": "Mimosa, tulipanes y cuándo tiene sentido regalar", "img": "mimosa", "color": "amarillo"},
    {"slug": "dia-del-padre", "name": "Día del Padre", "small": "19 mar · jun", "desc": "Flores para papá y la fecha en cada país", "img": "girasol", "color": "azul"},
    {"slug": "sant-jordi", "name": "Sant Jordi", "small": "23 abr", "desc": "Por qué se regala una rosa y un libro", "img": "rosa-roja", "color": "rojo"},
    {"slug": "dia-de-la-madre", "name": "Día de la Madre", "small": "may · oct", "desc": "Qué flores regalar y la fecha en cada país", "img": "peonia", "color": "rosa"},
    {"slug": "dia-del-maestro", "name": "Día del Maestro", "small": "15 may y más", "desc": "Qué flores regalar a tu profe y cuándo es en cada país", "img": "ramo-silvestre", "color": "amarillo"},
    {"slug": "dia-de-la-novia", "name": "Día de la Novia", "small": "1 ago", "desc": "El segundo San Valentín de Latinoamérica", "img": "rosa-rosa", "color": "rosa"},
    {"slug": "amor-y-amistad", "name": "Amor y Amistad", "small": "3.er sáb sep", "desc": "El San Valentín de Colombia, para pareja y amigos", "img": "ramo-rosas", "color": "rojo"},
    {"slug": "todos-los-santos-dia-de-muertos", "name": "Todos los Santos y Día de Muertos", "small": "1 y 2 nov", "desc": "Crisantemo y cempasúchil", "img": "cempasuchil", "color": "naranja"},
    {"slug": "nochebuena", "name": "Nochebuena", "small": "8 dic", "desc": "La flor mexicana de la Navidad", "img": "nochebuena", "color": "rojo"},
    {"slug": "virgen-de-guadalupe", "name": "Virgen de Guadalupe", "small": "12 dic", "desc": "Por qué se llevan rosas a la Basílica", "img": "rosa-roja", "color": "rojo"},
    {"slug": "flores-para-cumpleanos", "name": "Flores para cumpleaños", "small": "Todo el año", "desc": "Qué ramo regalar según la persona", "img": "ramo-tulipanes", "color": "rosa"},
    {"slug": "flores-para-aniversario", "name": "Flores para aniversarios", "small": "Todo el año", "desc": "Qué flores regalar según los años juntos", "img": "ramo-rosas", "color": "rojo"},
    {"slug": "flores-para-condolencias", "name": "Flores de condolencias", "small": "Cuando hace falta", "desc": "Qué flores enviar a un funeral y qué escribir", "img": "lilium", "color": "blanco"},
    {"slug": "significado-colores-flores", "name": "Significado de los colores", "small": "Todo el año", "desc": "Qué dice cada color y cuándo regalarlo", "img": "ramo-tulipanes", "color": "rosa"},
    {"slug": "flores-de-navidad", "name": "Flores de Navidad", "small": "dic", "desc": "Nochebuena, amarilis, eléboro y qué regalar", "img": "nochebuena", "color": "rojo"},
    {"slug": "flor-de-cada-mes-de-nacimiento", "name": "Flor de cada mes de nacimiento", "small": "Todo el año", "desc": "La flor de tu mes, como tu piedra", "img": "ramo-silvestre", "color": "rosa"},
    {"slug": "flores-blancas", "name": "Flores blancas", "small": "Todo el año", "desc": "Significado y cuándo regalarlas (y cuándo no)", "img": "alcatraz", "color": "blanco"},
    {"slug": "flores-rojas", "name": "Flores rojas", "small": "Todo el año", "desc": "Amor y pasión más allá de la rosa", "img": "rosa-roja", "color": "rojo"},
    {"slug": "flores-rosas", "name": "Flores rosas", "small": "Todo el año", "desc": "Cariño, gratitud y ternura en un ramo", "img": "rosa-rosa", "color": "rosa"},
    {"slug": "flores-para-graduacion", "name": "Flores para graduación", "small": "jun · jul · dic", "desc": "Qué ramo regalar a quien se gradúa", "img": "gerbera", "color": "amarillo"},
    {"slug": "flores-para-boda", "name": "Flores para boda", "small": "Todo el año", "desc": "Ramo de novia, flores de temporada y significado", "img": "ranunculo", "color": "blanco"},
]
